
version: '3.3'
services:

  website:
    ports:
      - 8000:8000

  back:
    build:
      context: ./back
      target: base
    command: yarn dev
    volumes:
      # Mount source code to restart app on change
      - ./back/src:/app/src
      - ./back/nodemon.json:/app/nodemon.json
      # Persist data (user sessions) between restarts
      - ./data:/app/data
    ports:
      - 8001:8001
    environment:
      - NODE_ENV=

  captionsdb:
    volumes: 
      - 'captionsdb:/data/db'

volumes: 
  captionsdb:
    external: true
