
version: '3.3'

services:

  website:
    build: ./website
    container_name: captions-website
    links:
      - back
    networks: 
      - default
    environment: 
      - LISTEN_PORT=8000
      - API_HOST=back
      - API_PORT=8001

  back:
    build: ./back
    container_name: captions-back
    links:
      - captionsdb
    user: "node"
    
    networks: 
      - default

    environment:
      - NODE_ENV=production
      - PORT=8001
      - DB_URL=mongodb://captions:${DB_PASSWORD}@captionsdb:27017/

      - SESSION_SECRET=${SESSION_SECRET}
      - TWITCH_OWNERID=${TWITCH_OWNERID}
      - TWITCH_CLIENTID=${TWITCH_CLIENTID}
      - TWITCH_CLIENTSECRET=${TWITCH_CLIENTSECRET}
      - TWITCH_SECRET=${TWITCH_SECRET}
      - TWITCH_REDIRECT_URI=${TWITCH_REDIRECT_URI}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}

  captionsdb:
    image: mongo
    container_name: captions-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=captions
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}











